### ISSUE TITLE
compatibility and examples

### ISSUE THREAD

**Issue by RainerHeintzmann** [emmt/OptimPackNextGen.jl#7]
Thanks for writing such a nice routine. I wonder whether it makes sense trying to make it compatible to the standard `Optim.jl` interface and potentially integrate it into `Optim.jl`?
Also the LineSearch part seems not to agree to the interface of `LineSearches.jl` but it might be useful to adhere to a common interface. What do you thin?

I had a bit of a difficult time to get a first example running. A small example code demonstrating the use may be very helpful.

Do you know, if the spectral projected gradient (SPD) may be useful for accelerated deconvolution applications? I do not really understand the purpose but I imagine that a projection into a different space may lead to large speedups?

**Comment by emmt** [comment]
I wrote VMLMB in Julia for our needs (image reconstruction and inverse problems) and, at that time, I wanted to be free from other software constraints. It may be a good idea to integrate it in `Optim.jl` at some time.  I am currently implementing VMLMB in a few other languages (like Matlab) to share this algorithm with my collegues and to purify the code (the method has a long history).  I am also testing it against other methods such as L-BFGS-B.  Any feedback by other users is very valuable and I appreciate that. 

The SPD method is mostly suitable to impose other convex constraints than separable bounds. It is a first order method and should not be as fast as variable metric algorithms (2nd order methods) when dealing with separable bound constraints.  If you have a problem with such non-separable constraints,SPD is easy to use (you just have to provide a projecteor on the feasible set, the objective function and its gradient) but may not be tha most efficient method. But this may depend on the specific problem to solve of course.

**Comment by emmt** [comment]
Otherwise, you are right, I should certainly provide examples. There are some examples in the test directory but not with lots of explanations...

**Comment by RainerHeintzmann** [comment]
Great! Thanks for the explanation. Let me know, once it is integrated into Optim.jl.
